---
- name: Configure chrony
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: Restart chrony

- name: Restart chrony after config change
  service:
    name: "{{ chrony_service_name }}"
    state: restarted
  become: true
  when: false
