---
- name: Set chrony variables
  set_fact:
    chrony_config_path: "{{ '/etc/chrony/chrony.conf' if ansible_facts['os_family'] == 'RedHat' else '/etc/chrony.conf' }}"
    chrony_service_name: "{{ 'chronyd' if ansible_facts['os_family'] == 'RedHat' else 'chrony' }}"

- name: Include chrony tasks
  include_tasks: "{{ _action }}.yml"
  when: "_action is defined"
  tags: chrony
