---
- name: Stop chrony service
  service:
    name: "{{ chrony_service_name }}"
    state: stopped
    enabled: false
  become: true
  failed_when: false

- name: Disable chrony service
  systemd:
    name: "{{ chrony_service_name }}"
    state: stopped
    enabled: false
  become: true
  failed_when: false

- name: Remove chrony package
  package:
    name: chrony
    state: absent
  become: true
  failed_when: false

- name: Remove chrony configuration
  file:
    path: "{{ chrony_config_path }}"
    state: absent
  become: true
  failed_when: false
  changed_when: false
