---
- import_playbook: gather-facts.yml


# - name: Prechecks
#   hosts: all
#   gather_facts: false
#   roles:
#     - role: prechecks
#       when: "(_action is undefined) or (_action == 'prechecks')"
#   tags: prechecks

# - name: Apply role chrony
#   gather_facts: false
#   hosts:
#     - chrony-server
#     - chrony
#     - "&enable_chrony_True"
#   serial: "{{'{{ ansible_serial|default(\'0\') }}'}}"
#   roles:
#     - role: chrony
#       tags: chrony
#       when: "enable_chrony | bool"

- name: Apply role {{cookiecutter.rolename}}
  gather_facts: false
  any_errors_fatal: true
  hosts: all
  serial: "{{'{{ ansible_serial|default(\'0\') }}'}}"
  roles:
    - role: {{cookiecutter.rolename}}
      tags: {{cookiecutter.rolename}}
