---
prechecks_supported_os:
  - RedHat
  - CentOS
  - Debian
  - Ubuntu
  - Rocky
  - AlmaLinux

prechecks_python_packages:
  - python3
  - python3-pip

prechecks_required_commands:
  - docker

prechecks_docker_min_version: "20.10"
